export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/manage"
export * from "@/pages/dashboard/schedule"
export * from "@/pages/dashboard/communication"
export * from "@/pages/dashboard/announcements"
export * from "@/pages/dashboard/tripplanner"
export * from "@/pages/dashboard/create-announcement"
export * from "@/pages/dashboard/settings"
export * from "@/pages/dashboard/feedback-and-support"
